version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Node.js version"
      - node -v
  build:
    commands:
      - echo "Running build phase"
      - node app.js  # Only for demo, remove in prod
  post_build:
    commands:
      - echo "✅ Build completed successfully"

artifacts:
  files:
    - app.js
    - buildspec.yml
