version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing Node.js dependencies"
      - npm install
  build:
    commands:
      - echo "Build complete"
  post_build:
    commands:
      - echo "Build phase finished"

artifacts:
  files:
    - '**/*'
